name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install
        run: uv sync

      - name: Lint
        run: uv run ruff check .

      - name: Type check
        run: uv run mypy .

      - name: Test
        run: uv run pytest

  build:
    name: Build .pyz
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install shiv
        run: pip install shiv uv

      - name: Build .pyz
        run: |
          mkdir -p build
          uv run shiv -o build/mid.pyz \
            -p '/usr/bin/env python3' \
            -e mid.main:main .

      - uses: actions/upload-artifact@v4
        with:
          name: mid.pyz
          path: build/mid.pyz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - run: ls -laR

      - name: Create release
        id: meta
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          gh release create "mid/${SHORT_SHA}" \
            --repo ${{ github.repository }} \
            --title "Release mid/${SHORT_SHA}" \
            mid.pyz/mid.pyz
        env:
          GH_TOKEN: ${{ github.token }}
